jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:stitch-tap-tester
    steps:
      - checkout
      - run:
          name: 'Setup virtual env'
          command: |
            python3 -mvenv /usr/local/share/virtualenvs/tap-ga4
            source /usr/local/share/virtualenvs/tap-ga4/bin/activate
            pip install -U pip setuptools
            pip install -e .[dev]
      - run:
          name: 'pylint'
          command: |
            source /usr/local/share/virtualenvs/tap-ga4/bin/activate
            # TODO: Adjust the pylint disables
            pylint tap_ga4 --disable 'broad-except,chained-comparison,empty-docstring,fixme,invalid-name,line-too-long,missing-class-docstring,missing-function-docstring,missing-module-docstring,no-else-raise,no-else-return,too-few-public-methods,too-many-arguments,too-many-branches,too-many-lines,too-many-locals,ungrouped-imports,wrong-spelling-in-comment,wrong-spelling-in-docstring,missing-class-docstring'
      - run:
          name: 'Unit Tests'
          command: |
            source /usr/local/share/virtualenvs/tap-ga4/bin/activate
            pip install nose coverage
            nosetests --with-coverage --cover-erase --cover-package=tap_ga4 --cover-html-dir=htmlcov tests/unittests
            coverage html
workflows:
  version: 2
  commit:
    jobs:
      - build:
          context: circleci-user
  build_daily:
    triggers:
      - schedule:
          cron: "0 13 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          context: circleci-user
